### ISSUE TITLE
[bug] Plant_Frostleaf does not have minimum and maxium allowed temps defined

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Syrchalis/Thrumkin#2]
Plant_Frostleaf does not have minimum and maximum allowed temps defined
instead it uses the default of all plants 0-58c (min-max)

this makes it not be plantable unless the temp is 10c+
also the description if confusing as you can tell from steam workshop comment

**Comment by Syrchalis** [comment]
This is not how plant temperatures work. They cannot simply be set, they are hard-coded in the game. Frostleaves use a custom class that returns different values for the temperature check. If that doesn't work for you something is messing with the plant's thingclass. So make sure you don't have a mod that overhauls all plants.
